#!/usr/bin/env bash
# ============================================================
# pr-drainage.sh — Generate safe gh commands to drain the PR backlog.
# ============================================================
# Output is a shell script the operator reviews + runs manually:
#
#   bash scripts/pipeline/pr-drainage.sh > /tmp/drainage.sh
#   # review /tmp/drainage.sh
#   bash /tmp/drainage.sh
#
# Categories (first match wins per PR):
#   ci-fail       non-draft + has FAILURE conclusion + age >= 48h  → auto-close
#   conflicting   mergeStateStatus∈{DIRTY,CONFLICTING} + age >= 6h → auto-close
#   stale-draft   isDraft + age >= 7d                              → auto-close (+ delete branch)
#   ready         non-draft + CI=PASS + mss∈{CLEAN,UNSTABLE}       → emitted COMMENTED
#   awaiting      non-draft + mss=CLEAN (no CI signal yet)         → emitted as comment-only
#
# Companion to audit-pr-backlog.sh (read-only). This script never executes
# gh pr close / merge itself — it ONLY prints commands to stdout.
#
# Exit codes
#   0 success   1 gh failure / empty payload   2 bad args
# ============================================================
set -uo pipefail

print_help() {
  sed -n '2,25p' "$0"
}

for arg in "$@"; do
  case "$arg" in
    -h|--help) print_help; exit 0 ;;
    *)         echo "Unknown arg: $arg" >&2; exit 2 ;;
  esac
done

PROJECT_DIR="/home/ubuntu/obsidian-plugins/obsidian-graph-island"
cd "$PROJECT_DIR" || { echo "ERROR: cannot cd to $PROJECT_DIR" >&2; exit 1; }

# Use a temp file for the JSON (same pattern as audit-pr-backlog.sh) — embedding
# JSON inside a python heredoc via shell expansion breaks on quotes / non-ASCII
# titles and on payloads near the arg-list limit.
TMP_JSON="$(mktemp -t pr-drainage.XXXXXX.json)"
trap 'rm -f "$TMP_JSON"' EXIT

if ! gh pr list --state open --limit 300 \
      --json number,title,headRefName,createdAt,isDraft,statusCheckRollup,mergeStateStatus \
      > "$TMP_JSON" 2>/dev/null; then
  echo "# ERROR: gh pr list failed (gh auth? offline? rate limit?) — no commands generated"
  exit 1
fi

if [[ ! -s "$TMP_JSON" ]] || [[ "$(<"$TMP_JSON")" == "[]" ]]; then
  echo "# No open PRs — backlog clean."
  exit 0
fi

cat <<'HEADER'
#!/usr/bin/env bash
# ------------------------------------------------------------
# Drainage script generated by pr-drainage.sh — REVIEW BEFORE RUNNING
#   Auto-close groups (uncommented, safe):  ci-fail, stale-draft, conflicting
#   Manual groups (commented out):          ready-to-merge, awaiting-review
# ------------------------------------------------------------
set -uo pipefail
HEADER

echo ""

python3 - "$TMP_JSON" <<'PY'
import json
import sys
from datetime import datetime, timezone

json_path = sys.argv[1]
with open(json_path, "r", encoding="utf-8") as f:
    prs = json.load(f)

now = datetime.now(timezone.utc)

categories = {
    "ci-fail":     [],
    "stale-draft": [],
    "conflicting": [],
    "ready":       [],
    "awaiting":    [],
}

for pr in prs:
    created_iso = pr.get("createdAt", "") or ""
    try:
        ca = datetime.fromisoformat(created_iso.replace("Z", "+00:00"))
        age_h = (now - ca).total_seconds() / 3600.0
    except Exception:
        age_h = -1.0
    pr["_age_h"] = age_h

    is_draft = bool(pr.get("isDraft", False))
    mss      = (pr.get("mergeStateStatus") or "").upper()
    rollup   = pr.get("statusCheckRollup") or []
    if not isinstance(rollup, list):
        rollup = []

    conclusions = []
    for c in rollup:
        if isinstance(c, dict):
            conclusions.append((c.get("conclusion") or "").upper())
    has_failure = any(c == "FAILURE" for c in conclusions)
    pending     = any(c in ("", "PENDING", "IN_PROGRESS", "QUEUED") for c in conclusions)
    has_pass    = bool(conclusions) and not has_failure and not pending

    # First match wins — order matters.
    if has_failure and not is_draft and age_h >= 48:
        categories["ci-fail"].append(pr)
    elif mss in ("DIRTY", "CONFLICTING") and age_h >= 6:
        categories["conflicting"].append(pr)
    elif is_draft and age_h >= 168:  # 7 days
        categories["stale-draft"].append(pr)
    elif (not is_draft) and mss in ("CLEAN", "UNSTABLE") and has_pass:
        categories["ready"].append(pr)
    elif (not is_draft) and mss == "CLEAN":
        categories["awaiting"].append(pr)
    # else: not a drainage candidate (fresh draft, pending CI, etc.) — skip

def safe_title(t, n=60):
    t = (t or "").replace("\n", " ").replace("\r", " ")
    # Strip backticks / dollar signs to keep generated comments shell-safe.
    t = t.replace("`", "'").replace("$", "S")
    return t[:n]

# ── ci-fail (auto-close) ──
if categories["ci-fail"]:
    print(f"# CI=FAIL non-draft PRs ({len(categories['ci-fail'])}) — auto-close")
    for pr in categories["ci-fail"]:
        print(f'gh pr close {pr["number"]} '
              f'--comment "auto-drainage: CI=FAIL >= 48h, no recovery path"  '
              f'# {int(pr["_age_h"])}h  {safe_title(pr.get("title"))}')
    print()

# ── stale-draft (auto-close + delete branch) ──
if categories["stale-draft"]:
    print(f"# Stale drafts >=7d ({len(categories['stale-draft'])}) — auto-close + delete branch")
    for pr in categories["stale-draft"]:
        print(f'gh pr close {pr["number"]} --delete-branch '
              f'--comment "auto-drainage: draft 7d+, autonomous noise"  '
              f'# {int(pr["_age_h"])}h  {safe_title(pr.get("title"))}')
    print()

# ── conflicting (auto-close) ──
if categories["conflicting"]:
    print(f"# Conflicting PRs >=6h ({len(categories['conflicting'])}) — auto-close")
    for pr in categories["conflicting"]:
        print(f'gh pr close {pr["number"]} '
              f'--comment "auto-drainage: merge conflict for 6h+, no rebase path"  '
              f'# {int(pr["_age_h"])}h  {safe_title(pr.get("title"))}')
    print()

# ── ready (commented out — operator must uncomment) ──
if categories["ready"]:
    print(f"# Ready-to-merge ({len(categories['ready'])}) — REVIEW + uncomment to run")
    for pr in categories["ready"]:
        print(f'# gh pr merge {pr["number"]} --admin --squash  '
              f'# {int(pr["_age_h"])}h  {safe_title(pr.get("title"))}')
    print()

# ── awaiting (info only — never an auto action) ──
if categories["awaiting"]:
    print(f"# Awaiting-review ({len(categories['awaiting'])}) — likely needs human attention")
    for pr in categories["awaiting"]:
        print(f'#   #{pr["number"]} ({int(pr["_age_h"])}h)  {safe_title(pr.get("title"), 50)}')
    print()

# ── footer summary ──
n_ci   = len(categories["ci-fail"])
n_sd   = len(categories["stale-draft"])
n_cf   = len(categories["conflicting"])
n_rd   = len(categories["ready"])
n_aw   = len(categories["awaiting"])
total  = n_ci + n_sd + n_cf + n_rd + n_aw
auto   = n_ci + n_sd + n_cf
manual = n_rd + n_aw

print(f"# ------------------------------------------------------------")
print(f"# Total candidates: {total}  "
      f"(auto-close: {auto} = ci-fail:{n_ci} + stale-draft:{n_sd} + conflicting:{n_cf}; "
      f"manual: {manual} = ready:{n_rd} + awaiting:{n_aw})")
print(f"# WARNING: review every line before running. This script will close PRs.")
PY
