/**
 * panel-defaults.ts
 *
 * Extracted default value groups from createDefaultPanel() to reduce
 * function size in PanelBuilder.ts (god object ratchet-down).
 */
import type { ClusterArrangement, ClusterGroupArrangement, ClusterGroupRule, SortKey, SortOrder } from "../types";

/** Default hover behavior and cluster layout settings. */
function defaultHoverAndClusterConfig() {
	return {
		hoverHops: 1,
		hoverHighlightTypes: {
			forwardLinks: true,
			backlinks: true,
			sharedTags: false,
			sameFolder: false,
		},
		hoverEdgeTypes: {
			link: true,
			semantic: false,
			tag: false,
			hasTag: false,
			similar: false,
			sibling: false,
			sequence: false,
			inheritance: true,
			aggregation: true,
		},
		commonQueries: [],
		clusterGroupRules: [] as ClusterGroupRule[],
		clusterArrangement: "inherit" satisfies ClusterArrangement,
		clusterGroupArrangement: "auto" satisfies ClusterGroupArrangement,
		clusterNodeSpacing: 3.0,
		clusterGroupScale: 3.0,
		clusterGroupSpacing: 2.0,
		fadeEdgesByDegree: false,
		edgeBundleStrength: 0.65,
		sortRules: [{ key: "degree" satisfies SortKey, order: "desc" satisfies SortOrder }],
		nodeRules: [],
		nodeShapeRules: [
			{ match: "isTag", shape: "triangle" },
			{ match: "default", shape: "circle" },
		],
	};
}

/** Default cable, navigation, overlay, and advanced display settings. */
function defaultAdvancedConfig() {
	return {
		cableBundleMode: "auto" as const,
		cableTrunkWidth: 12,
		cableTrunkAlpha: 0.25,
		cableSpacing: 14,
		cableFanWidth: 2.5,
		cableFanAlpha: 0.9,
		syncWithEditor: true,
		localGraphCenter: null,
		localGraphHops: 2,
		edgeWeightThickness: true,
		edgeLayerMode: false,
		focusMode: false,
		focusNodeId: null,
		syncViewId: null,
		annotations: [],
		bookmarkedNodes: [],
		edgeDirectionFilter: "all" as const,
		showPathfinderOverlay: true,
		showLegend: true,
		showOutOfBoundsIndicator: false,
		searchHistory: [],
		orphanClusterField: "",
		highlightMissingNeighbors: false,
		showGraphStats: false,
		showAncestryBreadcrumb: false,
		nodeSubLabelFields: "",
		hoverTooltipFields: "",
		hoverShowTitle: true,
		hoverShowMeta: true,
		hoverShowBody: false,
		savedSearchQueries: [],
		savedViewports: [],
		presetZoomLevel: 0,
		zoomSensitivity: 1.0,
		pinnedPositions: {},
		navHistory: [],
		navHistoryCursor: -1,
		semanticZoom: false,
		showTagBadges: false,
		highContrastMode: false,
		showImportanceRing: false,
		importanceMetric: "degree" as const,
		showRecencyMarker: false,
		recencyDays: 7,
		definitionField: "",
		clusterLabelDetail: "standard" as const,
		highlightPatterns: false,
		showBridgeNodes: false,
		focusLayout: false,
		showHierarchyBreadcrumb: false,
		showSimilarSuggestions: false,
		showStructureQuestions: false,
		showEntropyOverlay: false,
		showClusterCompare: false,
		multiSelectNodeIds: [],
		subgraphNodeIds: [],
		subgraphStack: [],
		showRelationMatrix: false,
		presentationMode: false,
		showNodeThumbnails: false,
		nodeIconField: "",
		nodeIconMap: {},
		focusConeEnabled: true,
		expandedNodes: [],
		analysisOverlay: "off" as const,
		showOntologyBackbone: false,
	};
}
